spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/accounts/**
        - id: task-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/tasks/**
        - id: authentication-service
          uri: http://localhost:8089
          predicates:
            - Path=/api/v1/jwt/**
        - id: frontend
          uri: http://localhost:8085
          predicates:
            - Path=/task-tracker/**
        - id: notification-service
          uri: http://localhost:8100
          predicates:
            - Path=/api/v1/notification/**



server:
  port: 8989